### PR TITLE
Coupled Propeller Movement in Aerostructural Case

### PR DESCRIPTION
**Pull request by bernardopacini**
## Purpose
This PR adds functionality to carry out an aerostructural analysis (and optimization) considering propeller movement. When implemented, the propeller location is tied to the wingbox structure so that it moves with the wing as the wing deflects. This is done by adding structural nodes to the structural mesh, but adding / subtracting fictitious aerodynamic nodes that are used by MELD to transfer loads and displacements between the aerodynamic and structural analyses.

The exact case setup, including mesh generation, is a bit convoluted, so I will add documentation for how to set up this type of problem.

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Other (please describe)

## Testing
I have tested that the functionality, and gradients, work as intended, but I have not added automated testing. I can add a test for this before the PR is merged once we finalize the implementation.

## Checklist

- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by bernardopacini** [comment]
The failed test is due to missing functionality that is needed within MPHYS. A [PR is already open](https://github.com/OpenMDAO/mphys/pull/108) to add these updates into MPHYS.

**Comment by bernardopacini** [comment]
I updated the pre-coupling group to add an error when the warper is requested in addition to masking. This should be ready to merge, though let me know if you have other comments / questions about it. I did not add a test, but I can if you'd like.

**Comment by friedenhe** [comment]
Great! Can you add some comments at the beginning of the new components and functions? Also, in some components, you have forward mode implementations like: `if mode == 'fwd':`. I suggest you add a comment there that mphys/dafoam does not support forward mode yet but the code is for future reference.

**Comment by friedenhe** [comment]
BTW: I think we should a add test for this new feature. Let me know if you need to update the test docker image and what version of dependencies you need.

**Comment by bernardopacini** [comment]
> BTW: I think we should a add test for this new feature. Let me know if you need to update the test docker image and what version of dependencies you need.

Would you prefer a new test, or simply add an actuator disk + movement to the current aerostructural test? In either case we will need an updated wingbox with RBE elements to the actuator disk.

**Comment by friedenhe** [comment]
> > BTW: I think we should a add test for this new feature. Let me know if you need to update the test docker image and what version of dependencies you need.
> 
> Would you prefer a new test, or simply add an actuator disk + movement to the current aerostructural test? In either case we will need an updated wingbox with RBE elements to the actuator disk.


I suggest we add the act movement to the current aerostruct test.

**Comment by bernardopacini** [comment]
> > > BTW: I think we should a add test for this new feature. Let me know if you need to update the test docker image and what version of dependencies you need.
> > 
> > 
> > Would you prefer a new test, or simply add an actuator disk + movement to the current aerostructural test? In either case we will need an updated wingbox with RBE elements to the actuator disk.
> 
> I suggest we add the act movement to the current aerostruct test.

I agree. I will modify the wingbox in the test and add a propeller. Since it is mostly a functionality test I won't refine the aerodynamic mesh for the actuator zone.

**Comment by bernardopacini** [comment]
I updated the aerostructural case to include the propeller-wing coupling as well as a parent + child FFD setup. I removed the AOA variable to do this as it is more realistic. I also updated the file slightly to match the new MELD and pyGeo versions, so I think we will need to update those in the DAFoam Docker image. I expect the MPHYS tests on the PR to fail now until we update the image as well as the wing BDF file.

**Comment by bernardopacini** [comment]
This PR is blocked by https://github.com/mdolab/pygeo/pull/144. Once that one is merged we can update the Docker image, verify these tests, and merge in this PR.

**Comment by bernardopacini** [comment]
The two upstream pyGeo PRs were merged in. I verified the functionality of the propeller motion with 1 and 2 propellers and I updated the MPHYS aerostructural test (sent offline). This PR should be good to go!

**Pull request merged**
